### ISSUE TITLE
Missing blogID

### ISSUE THREAD

**Issue by adsoink** [valse/gatsby-source-blogger#1]
On compile I'm getting an error that the blogID is missing. The code as far as I can tell is correct, and the error persists even when I move the API key and ID to a .env file versus being directly in the config.

Thoughts?

**Comment by valse** [comment]
Hi,
   this is the first time that I saw this error message; could you check the response from this GET API request please?

`https://www.googleapis.com/blogger/v3/blogs/{YOUR-BLOG-ID}?key={YOUR-API-KEY}`

**Comment by adsoink** [comment]
Thanks for getting back with me.

I get a success message and am able to explore the API via Postman no problem, and I also have a Wagtail implementation with the same data (moving to Gatsby because it makes better sense for the client). For some reason Gatsby/GraphiQL fails and I get the persistent message that the blogID is missing.

**Comment by valse** [comment]
I tried to update the packages: let me know if the error persist also with latest Google APIs. In meantime I try to get more infos about it.

**Comment by adsoink** [comment]
Thanks very much for that. I've updated everything on my end and still receive the error. It looks like the API key is being passed correctly, but not the blogID. GraphiQL is not returning any data, and defining a basic query either inside the app or in GraphiQL produces no results.

Is there a specific way I need to pass the ID in gatsby-config? I've tried multiple combinations (inputting a portion of the URL as protocol, using "?key=", etc...) and all produce the ID missing error.

**Comment by valse** [comment]
Hi, the new 1.0.1 version in online now.
This is my plugin config for example:
```js
{
   resolve: 'gatsby-source-blogger',
   options: {
     apiKey: `${process.env.BLOGGER_API_KEY}`,
     blogId: `${process.env.BLOGGER_BLOG_ID}`,
   },
}

**Comment by adsoink** [comment]
Installed 1.0.1 via yarn and the error persists. If I pull the master and install manually, the error goes away. We appear to be making a connection, but the posts can't be queried. The error I see when I run a query against "allBloggerPost" or "allBloggerPage" is that neither exist. Tried writing a scheme to define "allBloggerPost" and get the same result.

Feels like there might be something missing. Shouldn't "allBloggerPost" and "allBloggerPage" be available objects after the plugin has been imported?

**Comment by adsoink** [comment]
Oops. Noticed that your "master" doesn't have the gatsby-node file in the plugin root. Everything validates for me when the file is only in "src" (still can't access data), but not when it's in the root of the plugin. The blogID missing error persists.

**Comment by adsoink** [comment]
Nudging to see if we have an update on this. Been able to replicate the error locally as well as a remote development server.

**Comment by valse** [comment]
Hi adsoink... Could you please DM your BlogID? I'm curious to see this issue... I googled about it but with no luck.

**Comment by valse** [comment]
With your BlogID I've found and solved the issue, thanks.
I saw that your blog has a lot of posts and I added support to it too (before was limited to 500 posts).
Update to latest plugin version and let me know ;-)

**Comment by adsoink** [comment]
That's fantastic! Thank you!

The console errors are gone, though I have a persistent 400 error for the API request. Looks like the current version isn't generating nodes on build (i.e. "warn The gatsby-source-blogger plugin has generated no Gatsby nodes. Do you need it?"). Are there additional variables or dependencies that haven't been outlined in your documentation?

**Comment by adsoink** [comment]
Sorry... console error of "blogID" missing persists. Again tested by inputting the API and ID directly into the config file, as well as a .env and neither produce a connection to the API.

**Comment by adsoink** [comment]
Here's the terminal output - 

```
Error fetching posts Error: Missing required parameters: blogId
    at createAPIRequestAsync
(/Users/travis/st-blog/node_modules/googleapis-common/build/src/apirequest.js:106:15)
    at Object.createAPIRequest
(/Users/travis/st-blog/node_modules/googleapis-common/build/src/apirequest.js:44:16)
    at Resource$Posts.list
(/Users/travis/st-blog/node_modules/googleapis/build/src/apis/blogger/v3.js:848:44)
    at Object.exports.sourceNodes
(/Users/travis/st-blog/node_modules/gatsby-source-blogger/gatsby-node.js:48:40)
    at runAPI
(/Users/travis/st-blog/node_modules/gatsby/dist/utils/api-runner-node.js:225:37)
    at resolve
(/Users/travis/st-blog/node_modules/gatsby/dist/utils/api-runner-node.js:348:19)
    at Promise._execute
(/Users/travis/st-blog/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor
(/Users/travis/st-blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise
(/Users/travis/st-blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Promise.mapSeries.plugin
(/Users/travis/st-blog/node_modules/gatsby/dist/utils/api-runner-node.js:347:16)
    at tryCatcher (/Users/travis/st-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue
Error fetching pages Error: Missing required parameters: blogId
    at createAPIRequestAsync
(/Users/travis/st-blog/node_modules/googleapis-common/build/src/apirequest.js:106:15)
    at Object.createAPIRequest
(/Users/travis/st-blog/node_modules/googleapis-common/build/src/apirequest.js:44:16)
warn The gatsby-source-blogger plugin has generated no Gatsby nodes. Do you need it?
```

**Comment by valse** [comment]
Yesterday I was able to generate a copy of your blog locally: are you sure that you set all config right? Did you enabled the Blogger API v3 in the Google Cloud Platform for the correct project? Did you set some restriction for the API Key?
If you want share your project I can check your configuration.

**Comment by adsoink** [comment]
I'm unable to share the Google Cloud portion or the codebase outside of the organization. 

The API is restricted and yes, the Blogger API has been enabled. A "headless" version of this exists with the same credentials in a Python project, and I'm able to access the blog via the same API key and ID via Postman, so I'm not too concerned about the Google config.

Can you share an example .env and gatsby-config? We just need this to pick up the blogID...

**Comment by valse** [comment]
I mean the Gatsby project I'm sorry 😛
However you can check my blog's gatsby-config.js that use blogger source too:
https://github.com/valse/marcovalsecchi.it/blob/master/gatsby-config.js

**Comment by adsoink** [comment]
All good and yeah, I'm not able to share the codebase. 

Config is identical to your example. Are there additional variables in the .env file? A colleague spun up their own a little while ago and was also unsuccessful at getting a local copy. They also receive the warning on build as well as a 404.

**Comment by adsoink** [comment]
And now we have a winner!

Did a little futzing with the .env file and switched the order of how we called the API key and ID, putting the ID ahead of the API key. That netted us a response on Gatsby Develop, but the URL had _Undefined_ in place of the ID and Key. Took a look under the hood of your plugin and noticed a "Use Strict" call at the top. Commented that out, ran Gatsby Develop, and we are now connected.

Now that's sorted, two questions - 

1. How do I gracefully override the _max 500_ so I'm pulling down the whole of the blog?
2. Is the "use strict" necessary?

Thanks!!

**Comment by valse** [comment]
> And now we have a winner!

I'm happy to hear that!

> 1. How do I gracefully override the _max 500_ so I'm pulling down the whole of the blog?

There is no limit with latest plugin version... you can query all the posts!

> 2. Is the "use strict" necessary?

Strict mode is set automatically during the plugin build and I think is a must to all Gatsby ecosystem
