### ISSUE TITLE
Errors on failed image processing

### ISSUE THREAD

**Issue by orsi** [valse/gatsby-source-blogger#11]
<img width="968" alt="Screen Shot 2021-11-24 at 1 40 17 PM" src="https://user-images.githubusercontent.com/7156655/143296090-fcc50288-936a-4251-ba5f-4f6928a7f30f.png">

I occasionally got an error on build for failed processing images for this plugin, but now it is not going away. Is there an option to not error on failed image processing?

**Comment by valse** [comment]
Hi... try to delete the `.cache` folder when you switch from development and production build on the local environment.

**Comment by orsi** [comment]
Doesn't work, still throws errors and fails the process.

**Comment by orsi** [comment]
Is this plugin still maintained or should I start removing it from my project? It's been 6 months now with no indication of anything happening.

<img width="595" alt="Screen Shot 2022-04-18 at 3 36 17 PM" src="https://user-images.githubusercontent.com/7156655/163866017-e097bb61-15d7-4b52-9dba-52e958251da7.png">

**Comment by orsi** [comment]
You could probably just not throw an error here and swallow it: <img width="603" alt="Screen Shot 2022-04-18 at 3 48 18 PM" src="https://user-images.githubusercontent.com/7156655/163867507-3ddc399c-7791-42f6-8fdc-d04e78b5c244.png">

Not sure if it's needed to break the build if blogger serves an image that can't be processed.

**Comment by valse** [comment]
Hi @orsi, thanks for your help: the problem was the async execution inside a forEach statement... I switched to a forIn one and now it should work as expected.
I added also the `downloadImage` option to disable all the image downloads.
Let me know if I can mark this issue as solved, thanks.

**Comment by orsi** [comment]
Thank you! Currently upgrading the package now and will give you an update in a day or two while I test building :D

**Comment by orsi** [comment]
Haven't run into any issues since, so it looks like it's good!
